# Generated by Django 4.1.7 on 2023-04-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_etudiant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adm',
        ),
    ]
