# Generated by Django 4.1.7 on 2023-04-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_etudiant_prénom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('mot_pass', models.CharField(max_length=10)),
                ('titre_bleu', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='prénom',
        ),
    ]
