# Generated by Django 4.2 on 2023-04-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_prop_remove_etudiant_prénom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='nom',
            new_name='name',
        ),
    ]
