# Generated by Django 4.2 on 2023-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0006_rename_nom_etudiant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('mot_pass', models.CharField(max_length=10)),
                ('carte_etud', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
