# Generated by Django 4.2 on 2023-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_etud_delete_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.TextField()),
                ('etat', models.CharField(max_length=30)),
                ('prix', models.FloatField(max_length=20)),
                ('add', models.CharField(max_length=30)),
                ('numTel', models.CharField(max_length=30)),
            ],
        ),
    ]
