# Generated by Django 4.1.7 on 2023-04-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0008_anno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etud',
            new_name='Etudiant',
        ),
    ]
