# Generated by Django 4.1.7 on 2023-05-12 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_etudiant_etudiant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='etudiant_id',
             field=models.IntegerField(),
        ),
    ]
