# Generated by Django 4.1.7 on 2023-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_etudiant_etudiant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='etudiant_id',
           field=models.AutoField(primary_key=True)

        ),
    ]
